name: deploy nutblaster

on:
  workflow_dispatch:
  push:
    branches: [master]
    paths:
      - .github/workflows/deploy-nutblaster.yml
      - server/**.rs
      - Cargo.lock

concurrency:
  group: deploy-nutblaster
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v6

      - name: build
        run: |
          set -e
          cargo build --release --locked

      - name: copy binary
        uses: appleboy/scp-action@v1
        with:
          host: nutblast.schwung.us
          username: nutpuncher
          key: ${{ secrets.PUBLIC_INSTANCE_SSH_KEY }}
          source: target/release/nutblaster
          target: /tmp
          strip_components: 2

      - name: deploy
        uses: appleboy/ssh-action@v1
        with:
          host: nutblast.schwung.us
          username: nutpuncher
          key: ${{ secrets.PUBLIC_INSTANCE_SSH_KEY }}
          script: |
            set -e
            systemctl --user stop nutblaster-v1 || :
            cp /tmp/nutblaster nutblaster-v1
            systemctl --user start nutblaster-v1
